baseURL = "https://sjoukje.eth.limo/"
languageCode = "en-us"
title = "sjoukje.eth"
theme = "hugo-book"

# IPFS Specifics
relativeURLs = true
canonifyURLs = true

[params]
    BookLogo = "images/avatar.png"
    BookTitle = "sjoukje.eth"
    BookDescription = "CTO Data & AI | Thought Leader | Author"
    BookRepo = "https://github.com/sjoukjezaal/blog"
    BookEditPath = "edit/main/content"
    BookTheme = "auto"
    BookMenuBundle = "/menu"
    BookSection = "*"
    BookSearchConfig = { "indexed": true }

[[menu.before]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/sjoukjezaal"
    weight = 10
[[menu.before]]
    name = "X (Twitter)"
    url = "https://x.com/sjoukjezaal"
    weight = 20
[[menu.before]]
    name = "GitHub Profile"
    url = "https://github.com/sjoukjezaal"
    weight = 30

[taxonomies]
    category = "categories"
    tag = "tags"