baseURL = "/"
languageCode = "en-us"
title = "sjoukje.eth"
theme = "papermod"

# IPFS/Limo support:
relativeURLs = true
canonifyURLs = false

[params]
    env = "production"
    title = "sjoukje.eth"
    description = "Thought leader in AI, cloud, data and digital sovereignty"
    author = "sjoukje.eth"
    
    # PaperMod specifieke instellingen
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    showPostMeta = true
    
    [params.homeInfoParams]
        Title = "Hi there \U0001F44B"
        Content = "This is my digital archive: a sovereign collection of insights on technology, leadership, and the decentralized web. It serves as a permanent record of my journey through AI, Cloud, and Data, tied to my digital identity."
        

   [[params.socialIcons]]
        name = "x"
        url = "https://x.com/sjoukjezaal"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/sjoukjezaal"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/sjoukjezaal"

    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 10

    [[menu.main]]
        identifier = "books"
        name = "Books"
        url = "/books/"
        weight = 20

      [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 30