baseURL = "/"
languageCode = "en-us"
title = "sjoukje.eth"
theme = "hugo-book"

relativeURLs = true
canonifyURLs = false

[params]
    BookLogo = "images/avatar.png"
    BookTitle = "sjoukje.eth"
    BookDescription = "CTO Data & AI | Thought Leader | Author"
    BookRepo = "https://github.com/sjoukjezaal/blog"
    BookEditPath = "edit/main/content"
    BookTheme = "light"
    BookMenuBundle = "/menu"
    BookSection = "*"
    BookSearch = true

[[menu.after]]
  name = "---"
  url = ""
  weight = 90

[[menu.after]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/sjoukjezaal/"
  weight = 100

[[menu.after]]
  name = "X"
  url = "https://x.com/sjoukjezaal"
  weight = 110

[[menu.after]]
  name = "GitHub"
  url = "https://github.com/sjoukjezaal"
  weight = 120

[taxonomies]
    category = "categories"
    tag = "tags"