baseURL = "/"
languageCode = "en-us"
title = "sjoukje.eth"
theme = "papermod"

[params]
    env = "production"
    title = "sjoukje.eth"
    description = "Thought leader in AI, cloud, data and digital sovereignty"
    author = "sjoukje.eth"
    
    # PaperMod specifieke instellingen
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    
    [params.homeInfoParams]
        Title = "Hi there \U0001F44B"
        Content = "Welcome to my decentralized archive on AI, Cloud, and Data Leadership."

   [[params.socialIcons]]
        name = "x"
        url = "https://x.com/sjoukjezaal"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/sjoukjezaal"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/sjoukjezaal"